### ISSUE TITLE
value of crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX bigger than it should be

### ISSUE THREAD

**Issue by rubiksdot** [stef/pysodium#111]
I need to use `pysodium.crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX.value` in my code but I found that its value is not quite right.

The [libsodium docs](https://github.com/jedisct1/libsodium-doc/blob/dda1f2ff2a63073f34d606618b2d8e2ce291bec4/secret-key_cryptography/secretstream.md?plain=1#L164) say it should be ~256GB and my reading of the [libsodium code](https://github.com/jedisct1/libsodium/blob/93a6e79750a31bc0b946bf483b2ba1c77f9e94ce/src/libsodium/include/sodium/crypto_secretstream_xchacha20poly1305.h#L32) confirms but `pysodium.crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX` and `pysodium.crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX.value` both give me ~18.5EB which is a mite bigger than it should be.

I've got libsodium 1.0.18 (debian flavour) and pysodium 0.7.16 (pypi flavour). Another person confirmed with libsodium/pysodium 1.0.19 / 0.7.16 and a third with pysodium 0.7.16.

**Comment by stef** [comment]
thanks for reporting this bug! if you agree that 8d2c6d8 fixes it, please close this issue.

**Comment by rubiksdot** [comment]
Getting 274877906816 which appears right. Thank you for the fast fix. :)

**Comment by jedisct1** [comment]
As a side note, this is the maximum length of a *single message* (a call to `_push()`). So there are no practical limits.
