### ISSUE TITLE
ability to check version of pysodium in-code missing

### ISSUE THREAD

**Issue by rubiksdot** [stef/pysodium#112]
Given  #111 and the hopeful upcoming fix I wanted to add to my code a version check where I could kludge a value for where `pysodium.crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX.value` is broken and use it where it is fixed but there appears to be no way to do that programmatically.

Could this be added, please?

**Comment by stef** [comment]
this can be easily checked by actually just checking the value `pysodium.crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX` being correct, which should be 274877906816 - if it is not you can override this value yourself to the correct value.

something along the lines of

```python
if pysodium.crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX != 274877906816:
     pysodium.crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX = 274877906816
```

should do the job surgically.

i hope this answers your request adequately, if you agree, please close this issue.

**Comment by rubiksdot** [comment]
Chewing this. The whole point (at least to me) to these constants would be to avoid using raw values in one's code.

As such I would want to avoid that so the above solution wouldn't be one I'd welcome.

That said, checking for version and putting in a hard value is kind the same thing so at least for this use-case the ability to programmatically check the version of pysodium would be of little use.

So I guess since the underpinning reasons just went poof I guess that's that.
