### ISSUE TITLE
Python 3 support (revisited)

### ISSUE THREAD

**Issue by pohutukawa** [stef/pysodium#16]
Python 3 is becoming much more common.

Also the `pysodium3` mentioned in ticket https://github.com/stef/pysodium/issues/2 does not exist (any more).

I've just given it a try by installing the GitHub master, and it installed just fine via `python3 setup install`, and the 11 unit tests also ran fine using `nosetests3`.

Personally, I have only done a very brief test of the module itself, but it did import in the interactive Python3 shell, and getting random numbers has worked as well.

According to the revision history, a commit `5cd2f4a20d72fb31655908d0e6a05c6204abe4ab` was supposed to provide some Py3 support.

It would be nice if this package could also be made available to PyPI, which currently only hosts version 0.6.5.1 for Python 2.x.

**Comment by stef** [comment]
sorry to disappoint you, but i have no plans to support py3 myself, however contributions or forks doing so are welcome.

**Comment by ThomasWaldmann** [comment]
+1 for py3 support.

**Comment by stef** [comment]
sorry, still no plans. pls do not reopen this issue. if you care about py3 support, then 1/ either fork 2/ send pull requests that are super easy to review and merge.
