### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by ne0h** [stef/pysodium#27]
Is it possible that keypair derivation (`crypto_box_seed_keypair` in libsodium) is not implemented yet?
`crypto_box` is equivalent to `crypto_box_easy` in libsodium?

Thanks in advance!

**Comment by stef** [comment]
no it's not, patches are welcome.

**Comment by stef** [comment]
also, patches should include also proper testcases, and travis test should run without problems.

**Comment by ne0h** [comment]
No problem, I will do this. So `crypto_box_easy` is already included?

**Comment by stef** [comment]
according to https://github.com/stef/pysodium/blob/master/pysodium/__init__.py not

**Comment by stef** [comment]
added by reporter in 6568d8bffade1b68010257f38208199bc4386326
