### ISSUE TITLE
crypto_box(_open) confusion

### ISSUE THREAD

**Issue by 25A0** [stef/pysodium#38]
I'm trying to use `crypto_box` and `crypto_box_open` to let party A encrypt and sign data for party B.
From my understanding, the following code should work:

```
def test_cross_box():
    pkA, skA = pysodium.crypto_sign_keypair()
    pkB, skB = pysodium.crypto_sign_keypair()
    nonce = pysodium.randombytes(pysodium.crypto_box_NONCEBYTES)
    msg = "foo"
    c = pysodium.crypto_box(msg, nonce, pkB, skA)
    d = pysodium.crypto_box_open(c, nonce, pkA, skB)
    assert msg == d

```

However, the above code raises a `ValueError` in
`/usr/local/lib/python2.7/site-packages/pysodium/__init__.py:256: in crypto_box_open
    __check(sodium.crypto_box_open(msg, padded, ctypes.c_ulonglong(len(padded)), nonce, pk, sk))`

The unit test only seems to check for cases where the public and secret key are the same when calling `crypto_box` and `crypto_box_open`, and indeed the following code works:

```
def test_self_box():
    pkA, skA = pysodium.crypto_sign_keypair()
    nonce = pysodium.randombytes(pysodium.crypto_box_NONCEBYTES)
    msg = "foo"
    c = pysodium.crypto_box(msg, nonce, pkA, skA)
    d = pysodium.crypto_box_open(c, nonce, pkA, skA)
    assert msg == d

```

Am I missing something about how `crypto_box` should be used, or is this a bug?

Using python 2.7, pysodium 0.6.8, libsodium 1.0.9

**Comment by stef** [comment]
would you try out crypto_box_keypair instead of crypto_sign_keypair, and check if it works like this?

**Comment by stef** [comment]
i'm not sure you should reuse the keys for encryption and signing. so you need two keys and also use crypto_sign_keypair not only crypto_box_keypair.

**Comment by 25A0** [comment]
Thanks a lot! :)
Using `crypto_box_keypair` works flawlessly.
I admittedly didn't pay attention to the type of keypair I generated. Sorry for the noise
