### ISSUE TITLE
libsodium version checking ?

### ISSUE THREAD

**Issue by evadot** [stef/pysodium#40]
Hi,

Yesterday I had the unpleasant surprise to find my app non-working after the update of pysodium to 0.6.9.
After a bit I found that the introduction of the aead* function was the root of the problem.
I'm on FreeBSD and the libsodium package is still 1.0.8 (aead* functions where introduced in 1.0.9).

So we have two possibility : 
1) Check the libsodium version at runtime and raise something if we need an upgraded version
2) Only import function from libsodium based on the version

I will happily provide a patch depending on which way you prefer.

Cheers,

**Comment by stef** [comment]
damn. sorry man. sure, i think 2 is easier, but 1 is more informative for any user. do you have any of this ready? i was also thinking of putting the aead functions in a try except block, also a very cheap solution, which fails silently, which might not be a good idea again.

**Comment by evadot** [comment]
The problem for solution 2 is that we also need to check the lib version in the helper function.
An easy way is to have a "function" -> "libsodium version" relation table, which could be useful but also a pita to maintain.
Putting everything in a try/except block will work be I don't think this is a good solution.
The solution 1 I proposed it the simplest, right now for my app I've simply set pysodium==0.6.8 in my setup.py requires, it's just a matter of what you want to do, if you say clearly on the readme.md that you will closely follow the release of libsodium and update as soon as possible pysodium for it it's good for me (and I think for everyone else). It's really easy with pip to track a specific version (as long as you don't delete them).

I don't have any of the code ready (I don't like to do stuff for nothing :P) but as said before I'll provide any code you want based the decision you made.

P.S. : don't feel sorry for me all the problems happened in dev on my machine and not in production :)

**Comment by stef** [comment]
it seems that this patch fails for py3. can anyone who cares about py3 please have a look? thx.

**Comment by evadot** [comment]
This is weird because I only dev under python3.4, I'll look further.

**Comment by evadot** [comment]
Ok I wasn't in my venv when testing so I was using python2 ...
Let me fix this quick

**Comment by stef** [comment]
py3 is fixed with d6b96d7a9c365d3ab2b5e56b704362025ed1bc1c
