### ISSUE TITLE
Python3 support.

### ISSUE THREAD

**Issue by tacitus-aedifex** [stef/pysodium#52]
There are number of issues with the current implementation that prevent the use of pysodium in python3 applications.

I propose that we detect the python version at runtime and modify the wrapper functions to do the right thing for python2 and python3.  Most notably, the message.encode() calls need to be fixed.

**Comment by stef** [comment]
i have no intention to support other languages than python 2. if someone sends PRs for py3 support i only add them if they're super clean and do not interfere with py2 support.

**Comment by stef** [comment]
duplicate of #2 and #16
