### ISSUE TITLE
[Question] Can this wrapper make use of crypto_secretbox_easy

### ISSUE THREAD

**Issue by bufke** [stef/pysodium#58]
Sorry if this is a libsodium noob question - According to the [libsodium docs](https://download.libsodium.org/doc/secret-key_cryptography/authenticated_encryption.html) crypto_secretbox_easy is the suggested method to use for symmetric encryption. 

> The _easy and _detached APIs are faster and improve usability by not requiring padding, copying or tricky pointer arithmetic.

Is it possible to use pysodium with crypto_secretbox_easy? Is it intentionally left out or is this something a pull request would be welcome for? If I understand correctly, it's possible to simply not use the _easy functions but it creates a barrier to entry for new users and makes porting code between languages harder without 1 to 1 mappings for libsodium.

**Comment by stef** [comment]
crypto_secretbox_easy is a "workaround" for a c-ism/backward-compatibility, in python we can hide this and provide the same functionality with crypto_secretbox. if you want a one-to-one  mapping you could say crypto_secretbox_easy = crypto_secretbox.

i tried to document this in 02f87cc6cae62f0c37a3979eb22ec5a51fa3e26f
