### ISSUE TITLE
Harmonize the interface of crypto_aead_chacha20poly1305_* 

### ISSUE THREAD

**Issue by niamster** [stef/pysodium#61]
Not all of the crypto_aead_chacha20poly1305_* functions accept `None` for `ad`.

Has support:

- crypto_aead_chacha20poly1305_encrypt_detached
- crypto_aead_chacha20poly1305_decrypt_detached

Doesn't have support:

- crypto_aead_chacha20poly1305_encrypt
- crypto_aead_chacha20poly1305_decrypt
- crypto_aead_chacha20poly1305_ietf_encrypt
- crypto_aead_chacha20poly1305_ietf_decrypt

**Comment by stef** [comment]
with the merge of PR 62 i think this can be closed. pls confirm by closing, or comment on why not :) thx!
