### ISSUE TITLE
Inconsistent copyright for test/

### ISSUE THREAD

**Issue by mans0954** [stef/pysodium#64]
test/__init__.py is Copyright (c) 2001-2014 Acronis, Author Bulat Gaifullin (bulat.gaifullin@acronis.com), no license specified.

test/test_pysodium.py is Copyright (c) 2013-2014, Marsiske Stefan, license BSD-2-Clause.

It appears that both files were originally committed by @bgaifullin in commit 4fc0a48837738aa48fb0c42a6214bd7c3a2f2a1c and that the copyright and license for test/test_pysodium.py was changed to Copyright (c) 2013-2014, Marsiske Stefan, license BSD-2-Clause in commit 6e35c7c9a0397bf279fab71616471c5e840f5370, but that the details for test/__init__.py were left unchanged.

Please could you confirm that test/__init__.py is licensed under BSD-2-Clause, and perhaps consider making the copyright statements consistent?

Thanks.

Christopher Hoskin

**Comment by bgaifullin** [comment]
fixed in #65

**Comment by stef** [comment]
thanks for reporting and fixing so quickly.
