### ISSUE TITLE
crypto_secretbox_detached and crypto_secretbox_open_detached

### ISSUE THREAD

**Issue by berndb84** [stef/pysodium#96]
Hello,
I can not find the "detached" variants of the functions [`crypto_secretbox_detached `and `crypto_secretbox_open_detached`](https://libsodium.gitbook.io/doc/secret-key_cryptography/secretbox#detached-mode).
Is it possible to add this two functions?

**Comment by stef** [comment]
sure, it's actually quite easy, if you want you can try yourself, a good example is `crypto_box_detached` here: https://github.com/stef/pysodium/blob/master/pysodium/__init__.py#L675

**Comment by berndb84** [comment]
Ok, thanks. Should I add the functions in a development branch and open a pull request?

**Comment by stef** [comment]
damn firefox messes up the urlbar and fucks up copy pasting urls. added the correct url above, but include it also in this comment: https://github.com/stef/pysodium/blob/master/test/test_pysodium.py#L94 - this comment i will delete latest when closing the issue.

**Comment by berndb84** [comment]
@stef I have no permission to push my branch.
```
$ git push origin berndb84_dev
remote: Permission to stef/pysodium.git denied to berndb84.
fatal: unable to access 'https://github.com/stef/pysodium.git/': The requested URL returned error: 403
```

**Comment by stef** [comment]
sorry for the delayed answer i had some personal issues that kept me afk.
if you want to do a pull request you have to fork the repo and push your changes there and then open a pull request from there. i hope that works for you, if not, just post the patch here, and i'll apply it manually.
